<a href="https://colab.research.google.com/github/EdJunior79/projeto-brasileirao-ciencia-de-dados/blob/main/projeto_brasileirao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Criar o Dataframe dos placares**

In [ ]:
import pandas as pd
#utilizando a biblioteca pandas
df_jogos = pd.read_csv("dados_brasileirao/campeonato-brasileiro-full.csv")
#visualizar os nomes das colunas e numero
df_jogos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9165 entries, 0 to 9164
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  9165 non-null   int64
 1   rodata              9165 non-null   int64
 2   data                9165 non-null   object
 3   hora                9165 non-null   object
 4   mandante            9165 non-null   object
 5   visitante           9165 non-null   object
 6   formacao_mandante   4190 non-null   object
 7   formacao_visitante  4190 non-null   object
 8   tecnico_mandante    4555 non-null   object
 9   tecnico_visitante   4555 non-null   object
 10  vencedor            9165 non-null   object
 11  arena               9165 non-null   object
 12  mandante_Placar     9165 non-null   int64
 13  visitante_Placar    9165 non-null   int64
 14  mandante_Estado     9165 non-null   object
 15  visitante_Estado    9165 non-null   object
 16  arrecadacao         380 non-null    float64
dtypes: float64(1), int64(4), object(12)
memory usage: 1.2+ MB

##Numero de jogos

In [ ]:
df_jogos.shape[0]

9165

## Dados faltando

In [ ]:
df_jogos.isnull().sum()

ID                       0
rodata                   0
data                     0
hora                     0
mandante                 0
visitante                0
formacao_mandante     4975
formacao_visitante    4975
tecnico_mandante      4610
tecnico_visitante     4610
vencedor                 0
arena                    0
mandante_Placar          0
visitante_Placar         0
mandante_Estado          0
visitante_Estado         0
arrecadacao           8785
dtype: int64

In [ ]:
df_jogos = df_jogos.drop(columns=['arrecadacao'])

Como a arrecadaçâo está faltando na maioria dos jogos, vou remove-la e fazer um estudo se os dados de formação e técnico faltantes são mais novos ou mais antigos, já que eles seriam indispensaveis para uma analise mais aprofundada.

In [ ]:
df_jogos['data'] = pd.to_datetime(df_jogos['data'])
#transformei os textos de data em formato datetime
df_jogos['ano'] = df_jogos['data'].dt.year
#criei uma nova coluna chamada ano

df_jogos.groupby('ano')[['tecnico_mandante', 'tecnico_visitante', 'formacao_visitante','formacao_mandante']].apply(lambda x: x.isnull().mean()*100 )
#calculei a % de valores ausentes por ano

,tecnico_mandante,tecnico_visitante,formacao_visitante,formacao_mandante
ano,,,,
2003,100.000000,100.000000,100.000000,100.000000
2004,100.000000,100.000000,100.000000,100.000000
2005,100.000000,100.000000,100.000000,100.000000
2006,100.000000,100.000000,100.000000,100.000000
2007,100.000000,100.000000,100.000000,100.000000
2008,100.000000,100.000000,100.000000,100.000000
2009,100.000000,100.000000,100.000000,100.000000
2010,100.000000,100.000000,100.000000,100.000000
2011,100.000000,100.000000,100.000000,100.000000
2012,100.000000,100.000000,100.000000,100.000000
2013,100.000000,100.000000,100.000000,100.000000
2014,0.526316,0.789474,95.789474,95.789474
2015,0.263158,0.000000,0.000000,0.000000
2016,0.263852,0.000000,0.791557,0.791557
2017,0.000000,0.263158,0.263158,0.263158
2018,0.000000,0.000000,0.000000,0.000000
2019,0.000000,0.000000,0.000000,0.000000
2020,0.000000,0.000000,0.000000,0.000000
2021,0.000000,0.000000,0.000000,0.000000
2022,0.000000,0.000000,0.000000,0.000000
2023,0.000000,0.000000,0.000000,0.000000
2024,0.000000,0.000000,0.263158,0.263158
2025,0.000000,0.000000,0.000000,0.000000

A coluna de data foi convertida para o formato datetime, o que permitiu criar uma coluna com o ano. Com isso, foi possível analisar os valores ausentes ao longo dos anos. Observei que os dados de técnicos estão disponíveis a partir de 2014, enquanto as informações de formação das equipes só passam a ter uma boa quantidade de dados a partir de 2015. Por isso, optei por utilizar os dados a partir de 2015, garantindo maior consistência na análise.

In [ ]:
df_cartoes = pd.read_csv("dados_brasileirao/campeonato-brasileiro-estatisticas-full.csv")
#visualizar os nomes das colunas e numero
df_cartoes.isnull().sum()

partida_id             0
rodata                 0
clube                  0
chutes                 0
chutes_no_alvo         0
posse_de_bola      10762
passes                 0
precisao_passes    13066
faltas                 0
cartao_amarelo         0
cartao_vermelho        0
impedimentos           0
escanteios             0
dtype: int64

In [ ]:
df_cartoes = pd.read_csv("dados_brasileirao/campeonato-brasileiro-cartoes.csv")
#visualizar os nomes das colunas e numero
df_cartoes.isnull().sum()

partida_id       0
rodata           0
clube            0
cartao           0
atleta           6
num_camisa     386
posicao       1198
minuto           0
dtype: int64